============================= test session starts =============================
platform win32 -- Python 3.11.7, pytest-8.3.5, pluggy-1.5.0
rootdir: C:\Users\Zaya\Desktop\UWA-Zaya\2025\Course\Units\CITS5505\Assignment\5505-Group-gc2\gc_2_app
configfile: pytest.ini
plugins: anyio-4.4.0, flask-1.3.0
collected 4 items

tests\test_auth.py F...                                                  [100%]

================================== FAILURES ===================================
_______________________ test_login_success_sets_session _______________________

client = <FlaskClient <Flask 'app'>>
make_user = <function make_user.<locals>._factory at 0x000001F58B377920>

    def test_login_success_sets_session(client, make_user):
        make_user(username="alice", password="secret")
        resp = client.post(
            "/login",
            data={"username": "alice", "password": "secret"},
            follow_redirects=True,
        )
>       assert b"Login successful" in resp.data
E       assert b'Login successful' in b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-w...n>\n            </form>\n          </div>\n  </div>\n\n  <script src="/static/js/index.js"></script>\n</body>\n</html>'
E        +  where b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-w...n>\n            </form>\n          </div>\n  </div>\n\n  <script src="/static/js/index.js"></script>\n</body>\n</html>' = <WrapperTestResponse 2941 bytes [200 OK]>.data

tests\test_auth.py:11: AssertionError
=========================== short test summary info ===========================
FAILED tests\test_auth.py::test_login_success_sets_session - assert b'Login s...
========================= 1 failed, 3 passed in 0.45s =========================
